---
name: Trigger CircleCI (Push)
on:
  push
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: secretflow-yacl-ci
        id: secretflow-yacl-ci
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
